name: Generate Doxygen documentation

on:
  push:
    branches:
      - doxyDebug

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        
      - name: Generate documentation
        run: doxygen Doxyfile
        
      - name: Create docs/html directory (if missing)
        run: mkdir -p docs/html

      - name: Create .nojekyll file
        run: touch docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
